version: '3.8'
services:
  db:
    image: postgres:14.3
    container_name: minitrack-db
    environment:
      POSTGRES_DB: minitrack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    image: yourusername/minitrack-app:1.0.0
    container_name: minitrack-app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: minitrack
      DB_USERNAME: postgres
      DB_PASSWORD: password
    depends_on:
      - db

volumes:
  postgres_data:
